### ISSUE TITLE
Saving and naming sprites feature request

### ISSUE THREAD

**Issue by SHA65536** [hochbaum/vampire-survivors-tools#1]
Hey!
Nice library! Very useful for modders and people trying to fix their savefile.
What do you think about a tool to automatically cut and rename spirtes according to their item name?
Would help me very much with the information bot haha
Just a suggestion! Cheers!

**Comment by hochbaum** [comment]
Thank you! I actually thought of something like that yesterday. This repository is supposed to become a collection of useful tools for modding, so your idea would perfectly fit.

**Comment by hochbaum** [comment]
By the way: it would be cool and very helpful to me if you could specify your exact requirements :)

**Comment by SHA65536** [comment]
Hey! I just thought it would be cool to make a small tool to parse all the images in renderer/assets/img according to the coordinates in those json files. Basically just cut em / rename and maybe scale up? Since it's really pixelated and small it would be nice to not use interpolation when resizing. But it's up to you! :D
